(function(g){var window=this;'use strict';var Usb=function(a,b){a.qb("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.lv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.hh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.CS&&(b.lengthText?(e=b.lengthText||null,f=b.xw||null):b.lengthSeconds&&(e=g.KG(b.lengthSeconds),f=g.KG(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.ESa(d).type;var l=b instanceof g.CS?b.isLivePlayback:null,m=b instanceof g.CS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.SJ("Assistir a $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Wk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.qs};b instanceof g.BS&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.U(),c=b.D;
g.V.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Ao vivo"},
{I:"div",Ma:["ytp-autonav-upcoming-stamp"],ya:"Em breve"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",ya:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ya:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ya:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ya:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ua("click",this.onClick);this.Ua("keypress",this.onKeyPress)},l6=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.V({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ka(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ya:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Ao vivo"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],ya:"Em breve"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",ya:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",ya:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",ya:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",ya:"{{author_and_views}}"}]}]}]});
g.N(this,this.j);this.j.Ka(this.container.element);d||this.T(this.j.Ha("ytp-autonav-endscreen-link-container"),"click",this.pT);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({I:"div",S:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ka(this.container.element);this.B=new g.V({I:"div",S:"ytp-autonav-endscreen-button-container"});g.N(this,this.B);this.B.Ka(this.container.element);
this.cancelButton=new g.V({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancelar reprodu\u00e7\u00e3o autom\u00e1tica"},ya:"Cancelar"});g.N(this,this.cancelButton);this.cancelButton.Ka(this.B.element);this.cancelButton.Ua("click",this.S2,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.V({I:"a",Ma:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Reproduzir pr\u00f3ximo v\u00eddeo"},ya:"Assista agora"});g.N(this,this.playButton);this.playButton.Ka(this.B.element);this.playButton.Ua("click",this.pT,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Vsb(this,b)):this.J.createClientVe(this.playButton.element,
this,115130);this.D=new g.Tu(function(){Wsb(c)},500);
g.N(this,this.D);this.oT();this.T(a,"autonavvisibility",this.oT);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.R2),this.T(a,"onAutonavCoundownStarted",this.U9))},m6=function(a){var b=a.J.En(!0,a.J.isFullscreen());
g.lv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Ug(b));g.lv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.aL);g.lv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Mf());g.lv(a.J.getRootNode(),"countdown-running",a.al());g.lv(a.container.element,"ytp-player-content",a.J.Mf());g.ns(a.overlay.element,{width:b.width+"px"});if(!a.al()){a.J.Mf()?Xsb(a,Math.round(Ysb(a)/1E3)):Xsb(a);b=!!a.suggestion&&!!a.suggestion.qs;var c=a.J.Mf()||!b;
g.lv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.lv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.LF(a.B,a.J.Mf());g.lv(a.element,"ytp-enable-w2w-color-transitions",Zsb(a))}},Wsb=function(a){var b=Ysb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Xsb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.al()?a.select(!0):a.al()&&a.D.start()},Ysb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.aC;return-1===a||void 0===a?8E3:a}return 0<=a.J.Ps()?a.J.Ps():g.cJ(a.J.U().experiments,"autoplay_time")||1E4},Vsb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.s8;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Zsb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},Xsb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ha("ytp-autonav-endscreen-upnext-header");g.Pf(a);if(0<=b){b=String(b);var c="Pr\u00f3ximo v\u00eddeo em $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Pr\u00f3ximo v\u00eddeo em $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Jf("Pr\u00f3ximo v\u00eddeo em $SECONDS".slice(0,d)));var e=g.If("span");g.Zu(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Uf(e,b);a.appendChild(e);a.appendChild(g.Jf("Pr\u00f3ximo v\u00eddeo em $SECONDS".slice(d+c.length)));return}}g.Uf(a,"Pr\u00f3ximo")},
n6=function(a,b){g.V.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.V.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",ya:"Pr\u00f3ximo"},{I:"span",S:"ytp-upnext-title",ya:"{{title}}"},{I:"span",S:"ytp-upnext-author",ya:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Reproduzir pr\u00f3ximo v\u00eddeo"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
ya:"Reprodu\u00e7\u00e3o autom\u00e1tica pausada"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ha("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Tu(this.BH,5E3,this);this.B=0;var b=this.Ha("ytp-upnext-cancel");this.cancelButton=new g.V({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancelar reprodu\u00e7\u00e3o autom\u00e1tica"},ya:"Cancelar"});g.N(this,this.cancelButton);this.cancelButton.Ua("click",this.T2,
this);this.cancelButton.Ka(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.N(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ha("ytp-upnext-autoplay-icon");this.T(b,"click",this.U2);this.api.createClientVe(b,this,115130);this.qT();this.T(a,"autonavvisibility",this.qT);this.T(a,"mdxnowautoplaying",this.H$);this.T(a,"mdxautoplaycanceled",this.I$);g.lv(this.element,"ytp-upnext-mobile",this.api.U().B)},$sb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.aC;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ps()?a.api.Ps():g.cJ(a.api.U().experiments,"autoplay_time")||1E4},atb=function(a,b){b=$sb(a,b);
var c=Math,d=c.min;var e=(0,g.gD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.al()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.al()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ya:"Mais v\u00eddeos"}]});this.N=new g.V({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l6(this.player);g.N(this,this.B);this.B.Ka(this.element);a.getVideoData().Wf?this.j=this.B:(this.j=new o6(a),g.iU(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.V({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ka(this.element);this.D=new g.AK(this);g.N(this,this.D);g.N(this,this.table);this.table.Ka(this.element);this.table.show();g.N(this,this.N);this.N.Ka(this.table.element);this.hide()},q6=function(a){var b=a.Mf();
b!==a.G&&(a.G=b,a.player.ra("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r6=function(a,b){g.V.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],ya:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.l0();2===this.buttonType&&g.av(this.element,"ytp-continue-watching-button");this.Ua("click",this.onClick);this.Ua("videodatachange",this.l0);g.LF(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Xe=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r6(a,2);g.N(this,this.watchButton);this.watchButton.Ka(this.element);this.hide()},btb=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.V({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",ya:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ka(this.element);var b=a.getVideoData();this.subscribeButton=new g.xW("Inscreva-se",null,"Cancelar assinatura",null,!0,!1,b.Jl,b.subscribed,"trailer-endscreen",null,a,!1);g.N(this,this.subscribeButton);this.subscribeButton.Ka(this.j.Ha("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},t6=function(a){var b=a.U(),c=g.yK||g.NR?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.V.call(this,{I:"a",Ma:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",ya:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",ya:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",ya:"Ao vivo"},{I:"span",S:"ytp-videowall-still-info-duration",ya:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",ya:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",ya:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.AK(this);g.N(this,this.j);this.Ua("click",this.onClick);this.Ua("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.AK(this);g.N(this,this.B);this.K=new g.Tu(function(){g.av(b.element,"ytp-show-tiles")},0);
g.N(this,this.K);var c=new g.V({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Anterior"},V:[g.RF()]});g.N(this,c);c.Ka(this.element);c.Ua("click",this.Y2,this);this.table=new g.IF({I:"div",S:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ka(this.element);c=new g.V({I:"button",Ma:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Pr\u00f3ximo"},V:[g.SF()]});g.N(this,c);c.Ka(this.element);c.Ua("click",this.X2,this);a.getVideoData().Wf?this.j=new l6(a,!0):this.j=
new o6(a);g.N(this,this.j);g.iU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v6=function(a){return g.jU(a.player)&&a.UC()&&!a.D},w6=function(a){var b=a.Mf();
b!==a.N&&(a.N=b,a.player.ra("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.N(this,this.watchButton);this.watchButton.Ka(this.element);g.hhb(a)&&(this.j=new g.n2(a),g.N(this,this.j),this.B=new g.V({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.N(this,this.B),this.j.Ka(this.B.element),this.B.Ka(this.element));a.createClientVe(this.element,this,156914);this.hide()},ftb=function(a){g.PV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.AK(this);g.N(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.hC(g.WR(c))&&d&&!g.fU(a)?(this.B=!0,this.endScreen=new s6(a,g.WT(a))):a.od()?this.endScreen=new x6(a):ctb(a)?(this.D=!0,dtb(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.Wg?this.endScreen=new btb(a):this.endScreen=new n6(a);g.N(this,this.endScreen);g.iU(a,this.endScreen.element,4);etb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.MJ("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.NJ("endscreen"),function(e){b.onCueRangeExit(e)})},dtb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Ql&&a.C===b.Wf)return!1;a.j=b.Ql;a.C=b.Wf;return!0},ctb=function(a){a=a.U();
return a.ge&&!a.Wg},etb=function(a){a.player.zf("endscreen");
var b=a.player.getVideoData();b=new g.LJ(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.LJ(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.tf([b,c])};
g.bU.prototype.Ps=g.fa(16,function(){return this.app.Ps()});
g.R0.prototype.Ps=g.fa(15,function(){return this.getVideoData().kV});
g.XT.prototype.Er=g.fa(14,function(a){this.Ei().Er(a)});
g.UW.prototype.Er=g.fa(13,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.bY.prototype.Er=g.fa(12,function(a){this.overflowButton&&this.overflowButton.Er(a)});
g.XT.prototype.Fr=g.fa(11,function(a){this.Ei().Fr(a)});
g.ZW.prototype.Fr=g.fa(10,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.bY.prototype.Fr=g.fa(9,function(a){this.shareButton&&this.shareButton.Fr(a)});
g.XT.prototype.xB=g.fa(8,function(a){this.Ei().xB(a)});
g.qW.prototype.xB=g.fa(7,function(a){this.YQ!==a&&(this.YQ=a,this.hq())});
g.XT.prototype.wB=g.fa(6,function(a){this.Ei().wB(a)});
g.bY.prototype.wB=g.fa(5,function(a){this.XQ!==a&&(this.XQ=a,this.gq())});g.x(k6,g.V);k6.prototype.select=function(){this.J.Mo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.qD||void 0)&&this.J.logClick(this.element)};
k6.prototype.onClick=function(a){g.SU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.x(l6,g.V);g.k=l6.prototype;g.k.OG=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.Wk()),m6(this))};
g.k.al=function(){return 0<this.C};
g.k.EB=function(){this.al()||(this.C=Date.now(),Wsb(this),Usb(this.J,Ysb(this)),g.lv(this.J.getRootNode(),"countdown-running",this.al()))};
g.k.bx=function(){this.bq();Wsb(this);var a=this.j.Ha("ytp-autonav-endscreen-upnext-header");a&&g.Uf(a,"Pr\u00f3ximo")};
g.k.bq=function(){this.al()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.bq()};
g.k.pT=function(a){g.SU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ha("ytp-autonav-endscreen-link-container")&&(a=this.j.Ha("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.qb("innertubeCommand",this.K),this.bq()):this.select())};
g.k.S2=function(){this.J.logClick(this.cancelButton.element);g.dU(this.J,!0);this.G&&this.J.qb("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Vsb(this,b);var c;this.G=null==(c=b.M7)?void 0:c.command};
g.k.U9=function(a){if(Zsb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.SG(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.SG(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.SG(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.SG(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.SG(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.SG(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.lv(this.element,"ytp-w2w-animate",!0)}};
g.k.R2=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.lv(this.element,"ytp-w2w-animate",!1)};
g.k.oT=function(){var a=this.J.Mf();this.N&&this.Gb!==a&&g.LF(this,a);m6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ha("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Ug=function(a){return 400>a.width||459>a.height};g.x(n6,g.V);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.UC=function(){return!1};
g.k.Mf=function(){return!1};
g.k.uY=function(){return!1};g.x(o6,g.V);g.k=o6.prototype;g.k.BH=function(){this.notification&&(this.D.stop(),this.Uc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.OG=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.qT=function(){g.LF(this,this.api.Mf());this.api.logVisibility(this.element,this.api.Mf());this.api.logVisibility(this.Ha("ytp-upnext-autoplay-icon"),this.api.Mf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Mf())};
g.k.Q$=function(){window.focus();this.BH()};
g.k.EB=function(a){var b=this;this.al()||(g.qE("a11y-announce","Pr\u00f3ximo "+this.suggestion.title),this.B=(0,g.gD)(),this.j=new g.Tu(function(){atb(b,a)},25),atb(this,a),Usb(this.api,$sb(this,a)));
g.cv(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.al=function(){return!!this.j};
g.k.bx=function(){this.bq();this.B=(0,g.gD)();atb(this);g.av(this.element,"ytp-upnext-autoplay-paused")};
g.k.bq=function(){this.al()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.BH(),this.notification=new Notification("Pr\u00f3ximo",{body:this.suggestion.title,icon:this.suggestion.hh()}),this.C=this.T(this.notification,"click",this.Q$),this.D.start())}this.bq();this.api.nextVideo(!1,a)};
g.k.U2=function(a){!g.Tf(this.cancelButton.element,a.target)&&g.SU(a,this.api)&&(this.api.Mf()&&this.api.logClick(this.Ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.T2=function(){this.api.Mf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.dU(this.api,!0)};
g.k.H$=function(a){this.api.getPresentingPlayerType();this.show();this.EB(a)};
g.k.I$=function(){this.api.getPresentingPlayerType();this.bq();this.hide()};
g.k.xa=function(){this.bq();this.BH();g.V.prototype.xa.call(this)};g.x(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.D.T(this.player,"appresize",this.gC);this.D.T(this.player,"onVideoAreaChange",this.gC);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.rT);this.D.T(this.player,"onAutonavCancelled",this.V2);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.dU(this.player,!1);g.jU(this.player)&&this.UC()&&!this.C?(q6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.EB():3===this.videoData.autonavState&&this.j.bx()):(g.dU(this.player,!0),q6(this));this.gC()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.bx();q6(this)};
g.k.gC=function(){var a=this.player.En(!0,this.player.isFullscreen());q6(this);m6(this.B);g.lv(this.element,"ytp-autonav-cancelled-small-mode",this.Ug(a));g.lv(this.element,"ytp-autonav-cancelled-tiny-mode",this.dJ(a));g.lv(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.ns(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.lv(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.cT(this.videoData);b&&(this.j.OG(b),this.j!==this.B&&this.B.OG(b))}if(a&&a.length)for(b=0;b<gtb.length;++b){var c=gtb[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.N(this,this.videos[b]);this.videos[b].Ka(this.N.element)}}this.gC()}};
g.k.rT=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.bq(),this.Gb&&this.gC()):(this.K=!0,this.Mf()&&(2===a?this.j.EB():3===a&&this.j.bx()))};
g.k.V2=function(a){a?this.rT(1):(this.C=null,this.K=!1)};
g.k.UC=function(){return 1!==this.videoData.autonavState};
g.k.Ug=function(a){return(910>a.width||459>a.height)&&!this.dJ(a)&&!(400>=a.width||360>=a.height)};
g.k.dJ=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Mf=function(){return this.Gb&&g.jU(this.player)&&this.UC()&&!this.C};
var gtb=[1,3,2,4];g.x(r6,g.V);g.k=r6.prototype;g.k.l0=function(){switch(this.buttonType){case 1:var a="Assista outra vez no YouTube";var b=156915;break;case 2:a="Continue assistindo no YouTube";b=156942;break;default:a="Continue assistindo no YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.TU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.OR(b)){var c={};g.OR(b)&&g.QT(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.jP(c,b);a=g.dn(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Gb&&this.Z)};
g.k.show=function(){g.V.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.V.prototype.hide.call(this);this.logVisibility()};
g.k.Oc=function(a){g.V.prototype.Oc.call(this,a);this.logVisibility()};g.x(s6,n6);s6.prototype.show=function(){3!==this.player.getPlayerState()&&(n6.prototype.show.call(this),this.Xe.wB(!0),this.Xe.Fr(!0),this.J.U().Fe||this.Xe.Er(!0),this.J.logVisibility(this.element,!0),this.watchButton.Oc(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.Xe.wB(!1);this.Xe.Fr(!1);this.Xe.Er(!1);this.J.logVisibility(this.element,!1);this.watchButton.Oc(!1)};g.x(btb,n6);btb.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Jl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.x(t6,g.V);t6.prototype.select=function(){this.api.Mo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.qD||void 0)&&this.api.logClick(this.element)};
t6.prototype.onClick=function(a){if(g.OR(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Wk(),c={};g.XUa(this.api,c,"emb_rel_end");b=g.dn(b,c);g.TU(b,this.api,a)}else g.SU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Of?!1:b.D};g.x(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.lq();this.B.T(this.player,"appresize",this.lq);this.B.T(this.player,"onVideoAreaChange",this.lq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.RL);this.B.T(this.player,"onAutonavCancelled",this.W2);a=this.videoData.autonavState;a!==this.Y&&this.RL(a);this.B.T(this.element,"transitionend",this.lba)};
g.k.destroy=function(){g.wC(this.B);g.wb(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.cv(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.UC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Gb;n6.prototype.show.call(this);g.cv(this.element,"ytp-show-tiles");this.player.U().B?g.Vu(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.dU(this.player,!1);v6(this)?(w6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.EB():3===this.videoData.autonavState&&this.j.bx()):(g.dU(this.player,!0),w6(this));a!==this.Gb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Gb;n6.prototype.hide.call(this);this.j.bx();w6(this);a!==this.Gb&&this.player.logVisibility(this.element,!1)};
g.k.lba=function(a){a.target===this.element&&this.lq()};
g.k.lq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.cT(d)];if(e.length){g.av(this.element,"ytp-endscreen-paginate");var f=this.J.En(!0,this.J.isFullscreen());if(a=g.WT(this.J))a=a.Gh()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.ys(f,n,p);g.ns(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.OG(g.cT(this.videoData));this.j instanceof
l6&&m6(this.j);g.lv(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.Ie(q+this.C,c),0!==t){r=this.stills[h];r||(r=new t6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var w=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-v-4,E=Math.floor(n*(l+t)/a)-w-4;g.us(r.element,w,v);g.ys(r.element,E,A);g.ns(r.element,"transitionDelay",
(m+l)/20+"s");g.lv(r.element,"ytp-videowall-still-mini",1===t);g.lv(r.element,"ytp-videowall-still-large",2<t);t=Math.max(E,A);g.lv(r.element,"ytp-videowall-still-round-large",256<=t);g.lv(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.lv(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.$u(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,v),g.OR(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Wk(),v={},g.QT(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.dn(t,g.jP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.lv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Rf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a,b=(null==(a=this.player.U())?0:a.L("html5_ignore_null_autonav_suggestion"))?this.player.getVideoData(1):this.player.getVideoData();if(this.videoData!==b){var c;null==(c=this.player.U())||!c.L("html5_ignore_null_autonav_suggestion")||null!=b&&g.cT(b)?(this.C=0,this.videoData=b,this.lq()):this.player.ma("missg",{vid:(null==b?void 0:b.videoId)||"",cpn:(null==b?void 0:b.clientPlaybackNonce)||""})}};
g.k.X2=function(){this.C+=this.stills.length;this.lq()};
g.k.Y2=function(){this.C-=this.stills.length;this.lq()};
g.k.uY=function(){return this.j.al()};
g.k.RL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.bq(),this.Gb&&this.lq()):(this.G=!0,this.Gb&&v6(this)&&(2===a?this.j.EB():3===a&&this.j.bx()))};
g.k.W2=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.RL(1)}else this.D=null,this.G=!1;this.lq()};
g.k.Mf=function(){return this.Gb&&v6(this)};g.x(x6,n6);x6.prototype.gE=function(){var a;return null==(a=this.j)?void 0:a.gE()};
x6.prototype.show=function(){if(3!==this.player.getPlayerState()){n6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.gE();g.lv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.WT(this.player))||c.xB(!0);this.player.logVisibility(this.element,!0);this.watchButton.Oc(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;null==(a=g.WT(this.player))||a.xB(!1);this.player.logVisibility(this.element,!1);this.watchButton.Oc(!1)};g.x(ftb,g.PV);g.k=ftb.prototype;g.k.ju=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.od()||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.cT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!ctb(this.player)||d;a=a.Gk;c=this.player.ED();return d&&!a&&!c&&!b};
g.k.Mf=function(){return this.endScreen.Mf()};
g.k.G8=function(){return this.Mf()?this.endScreen.uY():!1};
g.k.xa=function(){this.player.zf("endscreen");g.PV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Ab().Ke.get("heartbeat"),d=g.cT(a);!d||b.videoId!==d.videoId||a.jT?(this.player.Mo(b.videoId,void 0,void 0,!0,!0,b),c&&c.pJ("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.PV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.PV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.ju()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){etb(this);this.D&&dtb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.N(this,this.endScreen),g.iU(this.player,this.endScreen.element,4))};g.OV("endscreen",ftb);})(_yt_player);
